### ISSUE TITLE
showing network connection status

### ISSUE THREAD

**Issue by katat** [hubiinetwork/hubii-core#341]
Alert as a notification when there is no network. This notification can be a sticker at the bottom, and it should update the network status when the network is back.

**Comment by liamaharon** [comment]
If we have a dedicated error indicator, we may not need to replace balance & other info with error messages anymore. See https://github.com/hubiinetwork/hubii-core/issues/624

**Comment by katat** [comment]
That is true. So we can display the cached balances instead.
