### ISSUE TITLE
Error fetching balance

### ISSUE THREAD

**Issue by HDauven** [hubiinetwork/hubii-core#624]
Hey! 

When I want to access my wallet, 'Error fetching balance' is displayed. When unlocking the wallet this message is still shown. When I click on the wallet, it'll show the following message: "There was an problem fetching this wallet's transaction history. Please try again later." Re-adding the wallet does not fix the issue.

Any ideas?

Hubii core version 0.7.1
Linux Manjaro with kernel 4.19

UPDATE:
'Error fetching balance' is sometimes displayed for a brief moment. 
I have two wallets imported in Hubii Core. The hardware wallet does not display this behavior. The private key imported wallet does.

Possibly an intermediate value passed through redux too early?

**Comment by liamaharon** [comment]
Thanks @HDauven for reporting this issue!
The cause appears to be upstream with our backend, I've notified the appropriate team members.

**Comment by evangwt** [comment]
me too.

Hubii core version 0.7.1
MacOS Mojave version 10.14

**Comment by HDauven** [comment]
> eporting this issue!
> The cause appears to be upstream with our backend, I've notified the appro

It seems to work again. Thanks!

**Comment by evangwt** [comment]
It just happened again. I think a log reporting feature is needed.

**Comment by liamaharon** [comment]
Are you still experiencing the issue? 

We've opted for now not to include logs for security reasons. It's difficult to guarantee that sensitive info like private keys won't be included.

**Comment by HDauven** [comment]
How about caching the last value in localStorage and displaying that with a small indicator saying that it is not the most up to date value? 

I randomly have short fetching issues on an imported wallet with a private key. I also imported a wallet via a Ledger hardware wallet which doesn't seem to have this issue.

**Comment by liamaharon** [comment]
Not a bad idea to display some kind of extra error indicator when there's a network outage rather than replacing the balances with an error message.

Thanks for the suggestion, could possibly be added to the scope of this issue https://github.com/hubiinetwork/hubii-core/issues/341
