### ISSUE TITLE
Remove pricing data for locked legacy ERC20 tokens (EOS, TRX)

### ISSUE THREAD

**Issue by oyvindp** [hubiinetwork/hubii-core#643]
Some projects including EOS and Tron were originally launched as erc20 tokens until mainnet launch and have since moved to their own "blockchains".

Their legacy erc20 tokens still exist on the Ethereum chain but have no functionality and may be locked within eth addresses that register to hubii core. Showing pricing data to these legacy tokens may not reflect users' actual holdings on these projects' mainnets.

**Comment by liamaharon** [comment]
Well spotted, thanks.

I've opened an issue in the (private) upstream repository responsible for the tokens list core uses, they should be removed soon.

**Comment by hubiierik** [comment]
EOS and TRX are likely to be excluded from our prices service by themselves when we get the price update process established. But until then, we can remove EOS by hand. TRX on the other side, is still is active so I think we should leave it be for now.
