### ISSUE TITLE
functionality

### ISSUE THREAD

**Issue by ValKos** [hubiinetwork/hubii-core#670]
Is it possible, when you send your funds into another address , to add a button that calculate remaining balance and place figure that shows max possible funds to send (given specific gas price)? Same in "nahmii deposit" tab. Thanks.
Like this:
![default](https://user-images.githubusercontent.com/30324699/50289584-5a5bd600-047a-11e9-8485-d6d46a8ad7ca.png)

**Comment by liamaharon** [comment]
Thanks for letting us know you would like to see this feature, we do too and it's on the TODO.

Closing this issue because it's a duplicate: https://github.com/hubiinetwork/hubii-core/issues/587.
