### ISSUE TITLE
Prices not updating to reflect current market prices

### ISSUE THREAD

**Issue by chris-kgs** [hubiinetwork/hubii-core#725]
The prices for both ETH and HBT no longer appear to be updating, and the values are based on prices from a week or two ago.

**Comment by katat** [comment]
Thanks @chris-kgs for reporting. I just had a check, it seems the prices are up-to-date. Could you tell us the version of hubii core that you are currently using? Also please check out the latest versions: https://github.com/hubiinetwork/hubii-core/releases

**Comment by chris-kgs** [comment]
Hi @katat - my version of Core is up to date.  Interestingly I know of two others having the same problem (though I am not certain if they updated to the latest version).  All three of us are running Core on Mac OS so could that have something to do with it?

**Comment by katat** [comment]
Hi @chris-kgs, we had a further investigation and did realize this is an issue on the price API. We will try to resolve this and let you know as soon as possible.

**Comment by katat** [comment]
Hi @chris-kgs, we have made a fix to this issue. Please feel free to re-open this if you found the prices are not up-to-date. I close this issue for now. Thanks.
