### ISSUE TITLE
Cannot transfer in Core via hardware wallet

### ISSUE THREAD

**Issue by chris-kgs** [hubiinetwork/hubii-core#730]
There has been a consistent, unending unless closed, lag with this screen when attempting to transfer a token. 

<img width="544" alt="screen shot 2019-02-22 at 3 34 18 pm" src="https://user-images.githubusercontent.com/38642251/53254315-18f7d900-36fe-11e9-8ee4-20350da2be0e.png">

**Comment by katat** [comment]
Hi @chris-kgs 
In order for us to investigate the issue, can you please provide us the following information:
 - Version of hubii core app
 - Which operation system are you using? Is it windows or mac?
 - Which hardware wallet you are using? Is it trezor or ledger nano s?

**Comment by chris-kgs** [comment]
* I am current on the Core updates- in case it's helpful I noticed this issue 5-6 weeks ago but did not report at the time

* Mac OS

* Trezor

**Comment by katat** [comment]
Thanks for the info.

I have tried to reproduce the issue with Trezor on Mac OS, but it works fine on my side. 

Some more questions:
1. Did you get any error message after clicking the send button? 
2. Has the token actually sent after clicking the send button? 
3. Does your Trezor work on the official Trezor wallet software for the token transfer?
4. Are you using the Trezor one or Trezor model T?

**Comment by chris-kgs** [comment]
Ah ha- it seems to be because the firmware was not updated.  Hubii Core was my primary option for interacting with the wallet, and so it did not notify me that new Trezor firmware was available.  I loaded it through Myetherwallet and was able to update the firmware.  That seems to have resolved the issue.  

Previously it would just lag on that screen after clicking "send," and would not advance me to the steps needed to be taken on the Trezor to send.  So no token would send.

**Comment by katat** [comment]
Thanks for letting us know this is solved by upgrading the firmware. We will put this issue as a backlog, and optimize the hubii-core to notify the necessary firmware updates for the hardware wallets.
