### ISSUE TITLE
Failed to Send Transaction error

### ISSUE THREAD

**Issue by chris-kgs** [hubiinetwork/hubii-core#743]
Using a Trezor with fully updated Hubii Core for Mac- firmware is also fully updated. 

<img width="485" alt="Screen Shot 2019-04-04 at 10 14 23 PM" src="https://user-images.githubusercontent.com/38642251/55563435-89940b80-5728-11e9-8a5f-c3d7bc0c2583.png">

**Comment by katat** [comment]
@chris-kgs Thanks for reporting this issue. I can confirm with the latest firmware, this issue can be reproduced. We are working to fix this ASAP.

**Comment by katat** [comment]
Hi @chris-kgs 
We have made a fix to this issue, please download the latest version. Thanks for your patience.

**Comment by katat** [comment]
Feel free to let us know if this issue occurs again even with the latest hubii-core. I close this issue for now.
