### ISSUE TITLE
Request for blockies

### ISSUE THREAD

**Issue by markbkk** [hubiinetwork/hubii-core#765]
We should add blockies throughout hubii core where appropriate. I would suggest at least in the following places:

- My wallets, for each wallet
- Contacts, for each contact
- Transfer, for an address selected or entered

See https://github.com/MyCryptoHQ/ethereum-blockies-base64 for examples

**Comment by katat** [comment]
Hi @markbkk 

Here are some screenshots for the places integrated with the blockie avatars. Please let me know if there are any adjustments needed.

![Screen Shot 2019-07-17 at 3 30 51 PM](https://user-images.githubusercontent.com/1587352/61356242-83293a00-a8a8-11e9-8c06-7d3ffa413a8a.png)

![Screen Shot 2019-07-17 at 3 31 21 PM](https://user-images.githubusercontent.com/1587352/61356290-99cf9100-a8a8-11e9-8b95-c45ba1df212b.png)

**Comment by katat** [comment]
@markbkk 

These are how they look when rounded corner applied:

![Screen Shot 2019-07-18 at 4 32 48 PM](https://user-images.githubusercontent.com/1587352/61442284-e46d0e00-a979-11e9-9ada-71aed6e2d9c3.png)
![Screen Shot 2019-07-18 at 4 33 16 PM](https://user-images.githubusercontent.com/1587352/61442286-e46d0e00-a979-11e9-8ebd-ea46ec1feaa7.png)
![Screen Shot 2019-07-18 at 4 33 31 PM](https://user-images.githubusercontent.com/1587352/61442287-e46d0e00-a979-11e9-82cb-01eba2267c40.png)
