### ISSUE TITLE
100% cpu usage

### ISSUE THREAD

**Issue by katat** [hubiinetwork/hubii-core#774]
The 100% CPU usage happens in certain circumstances as reported.
This could be caused by the accumulated API polls after running hubii core for a while.

**Comment by morfj** [comment]
I have not seen this recently so I suspect it **might** be related to my VPN/network situation while in Russia!

**Comment by katat** [comment]
Thanks for the follow up. 
I also tried to use the network setting in the chrome's console to simulate a slow network, but it was still not able to reproduce the performance issue. Nevertheless, I think the issue can be resolved once the API polls are replaced by the event API in the core.
