### ISSUE TITLE
Cannot confirm settlement

### ISSUE THREAD

**Issue by ValKos** [hubiinetwork/hubii-core#787]
Hi there, 
Help me please!
Can't confirm settlement. Challenge period is succesfully ended, and I try to withdraw NII to Ether layer by clicking "confirm settlement". When I click everything is fine, the app gives me a link to mine etherscan transaction , I monitor the etherscan process of mining, but in a minute or so, the error appears: Fail with error 'Payment seals not genuine [Validatable.sol:65]'.

**Comment by katat** [comment]
Hi @ValKos,
We will look into this and get back to you ASAP.

**Comment by katat** [comment]
Hi @ValKos, 

Could you please provide us your email address? We'd like to reach out to you and suggest a way to resolve this issue.

Thanks.

**Comment by ValKos** [comment]
Sure thing. 6501764@gmail.com

**Comment by jijordre** [comment]
Hi @ValKos,

I sent you an email with guide to solve the issue. As the issue you reported is not bug of hubii core we therefore close the issue. Please reach out by email if you need more assistance.

Regards,
Jens Ivar
