### ISSUE TITLE
Error message when probing state of settlement challenges at withdrawal time

### ISSUE THREAD

**Issue by jijordre** [hubiinetwork/hubii-core#809]
The withdrawal panel reports an error when validating the existence and state of ongoing settlement challenges. Also at the bottom of the panel the status "Synchronising settlement status..." and a spinner never disappears.

![bug-hubii-core-1 4 0](https://user-images.githubusercontent.com/2352109/92631095-29b47380-f2d1-11ea-800b-78fcac6e2631.png)

**Comment by jijordre** [comment]
The cause of the problem seems attributed to a change in error response of a smart contract function revert introduced in [go-ethereum@1.9.15](https://github.com/ethereum/go-ethereum/releases/tag/v1.9.15). A fix of the problem consist of updating nahmii-sdk to handle the new error response schema and values.

**Comment by jijordre** [comment]
Closed by #808.

**Comment by M1901** [comment]
Just installed 1.4.1 on Win10 and I have this problem...error message when clicking on "Complete settlement" looks pretty much like the one on the pic above. Any fix to this?

**Comment by jijordre** [comment]
@M1901,

Just a quick note to say that we revisit your issue with hubii-core in connection with the debugging of #813.

Cheers,
Jens Ivar
